Changed yum package python-dev name
Changed yum package python-dev name to python-devel since python-dev does not exist:

No package python-dev available.
Error: Nothing to do